### ISSUE TITLE
Update App icon

### ISSUE THREAD

**Issue by vedangj044** [vedangj044/ufo-sighting#1]
We need a good app icon for our application. You can paste the link of any icon you like in the comments. Once approved you need to submit a Pull Request for the same.

**Comment by studentoftech** [comment]
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.iconfinder.com%2Ficons%2F482623%2Faliens_flying_saucer_space_man_space_ship_ufo_icon&psig=AOvVaw0po2vMI-MXX767mF9p_1LD&ust=1607283668587000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPjgmrPMt-0CFQAAAAAdAAAAABAN

**Comment by vedangj044** [comment]
Hello, This looks a premium icon and that too with transparent background. Please look for more icons.

**Comment by studentoftech** [comment]
https://freedesignfile.com/372142-ufo-icon-vector/
What about this sir?

**Comment by vedangj044** [comment]
Good Suggestions. While I was having a look at it, I came across this icon and I think it fits the best. https://www.iconfinder.com/icons/1054946/ufo_spacecraft_spaceship_icon
@studentoftech I would be glad if you use this icon and add it to the app and make a PR. If you have any doubts please ask on our Gitter channel ( find the link in readme )

**Comment by deytulsi18** [comment]
Please assign the task to me I'll get back in a few hours today
