### ISSUE TITLE
Add ProgressBar to activity_main.xml

### ISSUE THREAD

**Issue by codeDamon** [vedangj044/ufo-sighting#24]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:
When the data is fetching from the api, the screen (RecyclerView) is empty.

### Expected Behaviour:
User should see a loading ui while the data from api is being fetched.

### Steps to reproduce:
* Add a ProgressBar in activity_main.xml.
* Make it visible untill the data is fetched.

### Result
This will improve User experience of the app.

### Do you want to work on this issue?
I can work on this issue.

**Comment by vedangj044** [comment]
Great, we do need this. Please make a PR. Do keep in mind the following this
1. The progress bar would be visible initially, and it would set to View.GONE when the data arrives, you can use the resultCount live data observer to get the event of when the data arrives. [find here](https://github.com/vedangj044/ufo-sighting/blob/7d0ac9e91fdc847484a5e538429f683d14ab78b3/app/src/main/java/com/vedangj044/frisson/MainActivity.kt#L50)
2. The color of the progress bar should be `@color/backdrop_text_color`
3. Use find view by id
