### ISSUE TITLE
Adding View Model

### ISSUE THREAD

**Issue by vedangj044** [vedangj044/ufo-sighting#7]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:
We have set up the paging data source and added retrofit.

### Expected Behaviour:
The next task is to add a view model

### Note:
Until now we have followed [this](https://blog.mindorks.com/paging-3-tutorial) tutorial. You can do the same and follow this tutorial for adding a view model.

**Comment by spacemonkey1101** [comment]
can I be assigned this issue?

**Comment by vedangj044** [comment]
@spacemonkey1101 Hey, if you are working on this issue, I have recently committed the list item UI. We have to use it as the view holder for the recycler view you would create, so implement accordingly, You can have a look in the #5

**Comment by spacemonkey1101** [comment]
yeah i will look into it!!

**Comment by spacemonkey1101** [comment]
Hey should I add the recyclerView Adapter as well?

**Comment by vedangj044** [comment]
As we are using paging we need to use PagingDataAdapter ( and not recylerViewAdapter ). If possible please add it.

I have shared the link to [this turorial ](https://blog.mindorks.com/paging-3-tutorial)  if u need any help.
