### ISSUE TITLE
Docs: Add Code of Conduct md file

### ISSUE THREAD

**Issue by deytulsi18** [vedangj044/ufo-sighting#9]
Can I add Code Of Conduct which would be suitable for this project?
I would refer https://www.contributor-covenant.org/version/1/4/code-of-conduct/
for the instructions.

**Comment by vedangj044** [comment]
Frankly, It won't be required. But there is no harm in it. Please add it and submit a PR

**Comment by deytulsi18** [comment]
Ok, please assign it to me.
